version: '3.6'
services:
  postgres_db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=trade_log
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
